# Generated by Django 5.2.1 on 2025-05-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_project_project_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appartment',
            old_name='name',
            new_name='appartment_name',
        ),
    ]
