# Generated by Django 5.2.1 on 2025-05-29 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_appartment_appartment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartements', to='api.project'),
        ),
    ]
