# Generated by Django 5.2.1 on 2025-05-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_appartment_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appartment',
            old_name='appartment_name',
            new_name='appartement_name',
        ),
    ]
