# Generated by Django 4.2.23 on 2025-07-03 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_adress_project_city_project_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='nb_appartements',
            new_name='nb_client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='project',
            name='city',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.DeleteModel(
            name='Appartment',
        ),
        migrations.AddField(
            model_name='client',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='api.project'),
        ),
    ]
