# Generated by Django 4.2.23 on 2025-07-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_client_rename_nb_appartements_project_nb_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.project'),
        ),
    ]
